Nimble-Institute/nimble-design-system

Readme.md
=> docs(docs change): docs change

src/components/nimbleAutoComplete/StyledWrappers.tsx
Change selection paper color to pure white
=> fix(nimble auto complete): chnage selection paper color

package.json, src/assets/icons/DeleteIcon.tsx, src/assets/icons/EditIcon.tsx, src/assets/icons/ExpandIcon.tsx, src/components/index.ts, src/components/nimbleMobileSearch/NimbleMobileSearch.tsx, src/components/nimbleMobleListView/CustomTheme.tsx, src/components/nimbleMobleListView/NimbleMobileListView.tsx, src/components/nimbleMobleListView/StyleWrappers.tsx, stories/NimbleMobileListView.stories.tsx, yarn.lock
Added Data grid for mobile viev with search, primary icons and infinite scroll.
=> feat(nimble mobile data grid): added data list for mobile

src/components/nimbleGaugeChart/NimbleGaugeChart.css, src/components/nimbleGaugeChart/NimbleGaugeChart.tsx, stories/NimbleGaugeChart.stories.tsx
=> feat(nimble gauge component): add segments to gauge chart

src/components/nimbleDataTable/NimbleDataTable.tsx, src/components/nimbleDataTable/StyledWrappers.tsx
Nimble Data table missing props added font , font sizes and rest
=> fix(nimble data table): font and sizes props

src/components/nimbleDialog/NimbleDialog.tsx, stories/NimbleDialog.stories.tsx
Added icon prop for main action button
=> fix(nimble dialog component): added icon prop

src/components/nimbleSelect/NimbleSelect.tsx, stories/NimbleSelect.stories.tsx
Added placeholder prop to nimble select field. This is optional prop
=> fix(nimble select): nimble Select field placeholder added

src/components/nimbleMobleListView/NimbleMobileListView.tsx
Mobile search view overflowX scrollbar appears
=> fix(unwanted scrollbar): remove scrollbar

src/components/nimbleDataTable/StyledWrappers.tsx
Added camal case column name and filter label as per the dev request\
=> fix(nimble data table): column name changes

src/components/nimbleDataTable/NimbleDataTable.tsx
Added new prop name, isEnableMultipleSort for enable disable multiple sort option
=> fix(nimble data table): enable disable multiple sort option

src/components/nimbleDialog/NimbleDialog.tsx
Added 3 different props for handle button, primary, close and secondary buttons
=> fix(nimble dialog component): added Props for action buttons

src/components/nimbleAutoComplete/NimbleAutoComplete.tsx, src/components/nimbleDateRange/NimbleDateRange.tsx, src/components/nimbleInput/NimbleInput.tsx, src/components/nimbleMobileSearch/NimbleMobileSearch.tsx, src/components/nimbleSelect/NimbleSelect.tsx, src/components/nimbleSwitch/NimbleSwitch.tsx
Added name attribute for all the input fields
=> fix(nimble form fields): formik integration

src/components/nimbleSelect/NimbleSelect.tsx, stories/NimbleSelect.stories.tsx
Added multiselect option for nimble select field
=> feat(nimble select with multiple option): enable Multi-select

src/components/nimbleDataTable/FilterInputItem.tsx, src/components/nimbleDataTable/NimbleDataTable.tsx, src/components/nimbleDataTable/StyledWrappers.tsx, src/components/nimbleSelect/CustomTheme.tsx, src/components/nimbleSelect/NimbleSelect.tsx, stories/NimbleDataTable.stories.tsx
Added select option for data table filter
=> feat(nimble data table): filter Select option added

.babelrc.json, package.json, src/components/nimbleDataTable/StyledWrappers.tsx, src/components/nimbleSelect/NimbleSelect.tsx, stories/NimbleDataTable.stories.tsx, yarn.lock
remove text transform main action button, remove svg attribute issue with adding babel plugin
=> fix(nimble data table): main Action text transform

src/components/nimbleInput/NimbleInput.tsx, src/components/nimbleMobileSearch/NimbleMobileSearch.tsx
Added forward ref and clear method. Then users can clear the input programatically from the parent component.
=> fix(nimple inputs): added forward ref with clear option

src/components/nimbleButton/NimbleButton.tsx, src/components/nimbleDialog/NimbleDialog.tsx
Added fontfamily as props to nimble button component. Then below issue automatically fixed
=> fix(nimble button): added font family

src/components/nimbleDataTable/NimbleDataTable.tsx, src/components/nimbleDataTable/StyledWrappers.tsx
Added row hover color and prop to data table. row hover effect woprking with webkit annimation with 500ms delay for cool  effect
=> fix(nimble data table): added Hover Effect to table row

src/components/nimbleAutoComplete/StyledWrappers.tsx
Added hover aria selected and webkit transition for the colors
=> fix(nimble autocomplete): added hover color issue fixes

src/components/nimbleAutoComplete/NimbleAutoComplete.tsx, src/components/nimbleAutoComplete/StyledWrappers.tsx, stories/NimbleAutocomplete.stories.tsx
Remove unwanted space on list box plus, added some enhancement of the component. Change controll component to un controlled component
=> fix(nimble autocomplete): remove unwanted space on list box

src/components/nimbleButton/NimbleButton.tsx, src/components/nimbleDialog/NimbleDialog.tsx, stories/NimbleButton.stories.tsx
Added new prop end icon, now users able to select start or end icon for the button
=> fix(nimble button component): added Icon position start and end

src/components/nimbleDataTable/NimbleDataTable.tsx
added 3 new props for enable custom action icons
=> fix(nimble data table): enable custom action icons

src/components/nimbleInput/NimbleInput.tsx
Added input type support email and automatic validation
=> fix(nimble input): added email type

.github/workflows/publish.yml
=> ci(change action): change action

src/components/nimbleInput/CustomTheme.tsx, src/components/nimbleInput/NimbleInput.tsx, stories/NimbleInput.stories.tsx
Added multiline and rowCount props to nimble Input field max length and props added
=> feat(added text area): nimble Input field added Text Area

src/components/nimbleDataTable/FilterInputItem.tsx, src/components/nimbleDataTable/NimbleDataTable.tsx, src/components/nimbleDataTable/StyledWrappers.tsx, src/components/nimbleDateRange/NimbleDateRange.tsx, stories/NimbleDataTable.stories.tsx
now users can add date-range option for filter.
=> feat(nimble data table): added date range option for table filter

src/components/nimbleInput/NimbleInput.tsx
=> fix(nimbleinput): nimbleInput email validation fix

src/components/nimbleDataTable/FilterInputItem.tsx, src/components/nimbleDataTable/NimbleDataTable.tsx, src/components/nimbleDataTable/StyledWrappers.tsx, stories/NimbleDataTable.stories.tsx
=> fix(nimble-datatable): add additional sorting functionality

src/components/nimbleDataTable/NimbleDataTable.tsx
Show main action button only if there's a main action callback
fix #189
=> fix(nimble-data-table): ability to hide Main action button

src/components/index.ts, src/components/nimbleBasicDataTable/NimbleBasicDataTable.tsx, src/components/nimbleBasicDataTable/StyledWrappers.tsx, src/components/shared/icons/SortIcon.tsx, stories/NimbleBasicDataTable.stories.tsx
=> Nimble basic data table

src/components/nimbleDataTable/NimbleDataTable.tsx
=> feat(nimble-data-table): ability to hide filter icon and filter headers

src/components/nimbleDataTable/FilterInputItem.tsx, src/components/nimbleDataTable/StyledWrappers.tsx
=> fix(nimble-data-table): fix font family and font size for search filters

src/components/nimbleDataTable/FilterInputItem.tsx
=> fix(nimble-data-table): capitalise filter placeholders

src/components/nimbleChip/NimbleChip.tsx
BREAKING CHANGE: change the prop name backgroundColor as background and fontColor as labelColor
=> fix(nimble chip): fix some prop issue

src/components/nimbleTab/NimbleTab.tsx, stories/NimbleTab.stories.tsx
=> feat(nimble-tab): allow specific tab to be active upon rendering

src/components/nimbleDataTable/StyledWrappers.tsx, yarn.lock
=> fix(nimble-data-table): add space between search input and action 

src/components/nimbleDatePicker/NimbleDatePicker.tsx, stories/NimbleDatePicker.stories.tsx
=> feat(nimble-date-picker): ability to set minimum selectable date

src/components/nimbleDatePicker/NimbleDatePicker.tsx, stories/NimbleDatePicker.stories.tsx
=> feat(nimble-date-picker): allow custom date format

src/components/nimbleDataTable/NimbleDataTable.tsx, src/components/nimbleDataTable/StyledWrappers.tsx
=> fix(nimble-data-table): fix spacing between action icons

src/components/nimbleDataTable/NimbleDataTable.tsx, stories/NimbleDataTable.stories.tsx
=> feat(nimble-data-table): allow to customize action icons based on a column value

src/components/nimbleDialog/NimbleDialog.tsx, stories/NimbleDialog.stories.tsx, yarn.lock
=> feat(nimble-dialog): ability to disable primary action button

src/components/nimbleDataTable/FilterInputItem.tsx, src/components/nimbleDataTable/NimbleDataTable.tsx, stories/NimbleDataTable.stories.tsx
=> feat(nimble-data-table): make multi-select available for column filters

src/components/nimbleTimeline/NimbleTimeline.tsx, src/components/nimbleTimeline/StyleWrappers.tsx, src/components/nimbleTimeline/timelineStyles.css, stories/NimbleTimeline.stories.tsx
Timeline changes
- new ledger ui, etc
=> Zb timeline changes

src/components/nimbleDataTable/NimbleDataTable.tsx
added selected rows as string and number array
=> fix(nimble data table): prop changes

src/components/nimbleAutoComplete/NimbleAutoComplete.tsx
=> fix(nimble-auto-complete): fix duplicate issue

src/assets/icons/ClearIcon.tsx, src/assets/icons/DropdownIcon.tsx, src/components/nimbleSelect/NimbleSelect.tsx
=> feat(component): given color prop for nimble select

src/components/nimbleRadioButton/NimbleRadioButton.tsx
=> feat: added disabled option to nimble radio button component

src/components/nimbleBasicDataTable/NimbleBasicDataTable.tsx
=> fix(nimble-basic-table): fix filtering issue
